<a href="https://colab.research.google.com/github/abdullah-621/pandas/blob/main/multiindex_objects.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
# can we have multiple index? Let's try
index_val = [('cse',2019),('cse',2020),('cse',2021),('cse',2022),('ece',2019),('ece',2020),('ece',2021),('ece',2022)]

a = pd.Series([1,2,3,4,5,6,7,8], index = index_val)
a
# a[('cse', 2020)]

(cse, 2019)    1
(cse, 2020)    2
(cse, 2021)    3
(cse, 2022)    4
(ece, 2019)    5
(ece, 2020)    6
(ece, 2021)    7
(ece, 2022)    8
dtype: int64

In [ ]:
# The problem?
a['cse']

KeyError: 'cse'

In [ ]:
# The solution -> multiindex series(also known as Hierarchical Indexing)
# multiple index levels within a single index

In [3]:
# how to create multiindex object
# 1. pd.MultiIndex.from_tuples()
index_val = [('cse',2019),('cse',2020),('cse',2021),('cse',2022),('ece',2019),('ece',2020),('ece',2021),('ece',2022)]
Multiindex = pd.MultiIndex.from_tuples(index_val)
Multiindex

# 2. pd.MultiIndex.from_product()
pd.MultiIndex.from_product([['cse','ece'], [2019,2020,2021,2022]])

MultiIndex([('cse', 2019),
            ('cse', 2020),
            ('cse', 2021),
            ('cse', 2022),
            ('ece', 2019),
            ('ece', 2020),
            ('ece', 2021),
            ('ece', 2022)],
           )

In [4]:
# creating a series with multiindex object

s = pd.Series([1,2,3,4,5,6,7,8], index=Multiindex)
s

cse  2019    1
     2020    2
     2021    3
     2022    4
ece  2019    5
     2020    6
     2021    7
     2022    8
dtype: int64

In [5]:
# how to fetch items from such a series
s[('cse',2019)]
s['cse']

2019    1
2020    2
2021    3
2022    4
dtype: int64

In [13]:
# unstack
temp = s.unstack()
temp

     2019  2020  2021  2022
cse     1     2     3     4
ece     5     6     7     8

In [7]:
# stack
temp.stack()

cse  2019    1
     2020    2
     2021    3
     2022    4
ece  2019    5
     2020    6
     2021    7
     2022    8
dtype: int64

In [8]:
# Multiindex Data fream

branch_df1 = pd.DataFrame(
    [
        [1,2],
        [3,4],
        [5,6],
        [7,8],
        [9,12],
        [10,13],
        [11,15],
        [12,20]
    ],
    index = Multiindex,
    columns = ['avg_packge', 'students']
)
branch_df1

          avg_packge  students
cse 2019           1         2
    2020           3         4
    2021           5         6
    2022           7         8
ece 2019           9        12
    2020          10        13
    2021          11        15
    2022          12        20

In [9]:
# Multiindex DataFream

branch_df2 = pd.DataFrame(
    [
      [1,2,0,0],
      [3,4,0,0],
      [5,6,0,0],
      [7,8,0,0],
    ],

    index = [2019, 2020, 2021, 2022],
    columns = pd.MultiIndex.from_product([['delhi', 'mumbai'], ['avg_packge', 'students']])

)

branch_df2

          delhi              mumbai
     avg_packge students avg_packge students
2019          1        2          0        0
2020          3        4          0        0
2021          5        6          0        0
2022          7        8          0        0

In [10]:
branch_df2.loc[2019]['delhi']

avg_packge    1
students      2
Name: 2019, dtype: int64

In [11]:
# Multiindex series and DataFream

branch_df3 = pd.DataFrame(
    [
      [1,2,0,0],
      [3,4,0,0],
      [5,6,0,0],
      [7,8,0,0],
      [9,10,0,0],
      [11,12,0,0],
      [13,14,0,0],
      [15,16,0,0],
    ],

    index = Multiindex,
    columns = pd.MultiIndex.from_product([['delhi', 'mumbai'], ['avg_packge', 'students']])

)

branch_df3

              delhi              mumbai
         avg_packge students avg_packge students
cse 2019          1        2          0        0
    2020          3        4          0        0
    2021          5        6          0        0
    2022          7        8          0        0
ece 2019          9       10          0        0
    2020         11       12          0        0
    2021         13       14          0        0
    2022         15       16          0        0

In [12]:
branch_df3.loc['cse']['delhi']['avg_packge'][2019]

np.int64(1)

# Stacking and Unstacking

In [22]:
branch_df3.stack(future_stack=True).stack(future_stack=True)

cse  2019  avg_packge  delhi      1
                       mumbai     0
           students    delhi      2
                       mumbai     0
     2020  avg_packge  delhi      3
                       mumbai     0
           students    delhi      4
                       mumbai     0
     2021  avg_packge  delhi      5
                       mumbai     0
           students    delhi      6
                       mumbai     0
     2022  avg_packge  delhi      7
                       mumbai     0
           students    delhi      8
                       mumbai     0
ece  2019  avg_packge  delhi      9
                       mumbai     0
           students    delhi     10
                       mumbai     0
     2020  avg_packge  delhi     11
                       mumbai     0
           students    delhi     12
                       mumbai     0
     2021  avg_packge  delhi     13
                       mumbai     0
           students    delhi     14
                       mumbai     0
     2022  avg_packge  delhi     15
                       mumbai     0
           students    delhi     16
                       mumbai     0
dtype: int64

In [25]:
branch_df3.unstack().unstack()

delhi   avg_packge  2019  cse     1
                          ece     9
                    2020  cse     3
                          ece    11
                    2021  cse     5
                          ece    13
                    2022  cse     7
                          ece    15
        students    2019  cse     2
                          ece    10
                    2020  cse     4
                          ece    12
                    2021  cse     6
                          ece    14
                    2022  cse     8
                          ece    16
mumbai  avg_packge  2019  cse     0
                          ece     0
                    2020  cse     0
                          ece     0
                    2021  cse     0
                          ece     0
                    2022  cse     0
                          ece     0
        students    2019  cse     0
                          ece     0
                    2020  cse     0
                          ece     0
                    2021  cse     0
                          ece     0
                    2022  cse     0
                          ece     0
dtype: int64