<a href="https://colab.research.google.com/github/abdullah-621/pandas/blob/main/multiindex_objects.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
# can we have multiple index? Let's try
index_val = [('cse',2019),('cse',2020),('cse',2021),('cse',2022),('ece',2019),('ece',2020),('ece',2021),('ece',2022)]

a = pd.Series([1,2,3,4,5,6,7,8], index = index_val)
a
# a[('cse', 2020)]

(cse, 2019)    1
(cse, 2020)    2
(cse, 2021)    3
(cse, 2022)    4
(ece, 2019)    5
(ece, 2020)    6
(ece, 2021)    7
(ece, 2022)    8
dtype: int64

In [3]:
# The problem?
# a['cse']

In [4]:
# The solution -> multiindex series(also known as Hierarchical Indexing)
# multiple index levels within a single index

In [5]:
# how to create multiindex object
# 1. pd.MultiIndex.from_tuples()
index_val = [('cse',2019),('cse',2020),('cse',2021),('cse',2022),('ece',2019),('ece',2020),('ece',2021),('ece',2022)]
Multiindex = pd.MultiIndex.from_tuples(index_val)
Multiindex

# 2. pd.MultiIndex.from_product()
pd.MultiIndex.from_product([['cse','ece'], [2019,2020,2021,2022]])

MultiIndex([('cse', 2019),
            ('cse', 2020),
            ('cse', 2021),
            ('cse', 2022),
            ('ece', 2019),
            ('ece', 2020),
            ('ece', 2021),
            ('ece', 2022)],
           )

In [6]:
# creating a series with multiindex object

s = pd.Series([1,2,3,4,5,6,7,8], index=Multiindex)
s

cse  2019    1
     2020    2
     2021    3
     2022    4
ece  2019    5
     2020    6
     2021    7
     2022    8
dtype: int64

In [7]:
# how to fetch items from such a series
s[('cse',2019)]
s['cse']

2019    1
2020    2
2021    3
2022    4
dtype: int64

In [8]:
# unstack
temp = s.unstack()
temp

     2019  2020  2021  2022
cse     1     2     3     4
ece     5     6     7     8

In [9]:
# stack
temp.stack()

cse  2019    1
     2020    2
     2021    3
     2022    4
ece  2019    5
     2020    6
     2021    7
     2022    8
dtype: int64

In [10]:
# Multiindex Data fream

branch_df1 = pd.DataFrame(
    [
        [1,2],
        [3,4],
        [5,6],
        [7,8],
        [9,12],
        [10,13],
        [11,15],
        [12,20]
    ],
    index = Multiindex,
    columns = ['avg_packge', 'students']
)
branch_df1

          avg_packge  students
cse 2019           1         2
    2020           3         4
    2021           5         6
    2022           7         8
ece 2019           9        12
    2020          10        13
    2021          11        15
    2022          12        20

In [11]:
# Multiindex DataFream

branch_df2 = pd.DataFrame(
    [
      [1,2,0,0],
      [3,4,0,0],
      [5,6,0,0],
      [7,8,0,0],
    ],

    index = [2019, 2020, 2021, 2022],
    columns = pd.MultiIndex.from_product([['delhi', 'mumbai'], ['avg_packge', 'students']])

)

branch_df2

          delhi              mumbai
     avg_packge students avg_packge students
2019          1        2          0        0
2020          3        4          0        0
2021          5        6          0        0
2022          7        8          0        0

In [12]:
branch_df2.loc[2019]['delhi']

avg_packge    1
students      2
Name: 2019, dtype: int64

In [13]:
# Multiindex series and DataFream

branch_df3 = pd.DataFrame(
    [
      [1,2,0,0],
      [3,4,0,0],
      [5,6,0,0],
      [7,8,0,0],
      [9,10,0,0],
      [11,12,0,0],
      [13,14,0,0],
      [15,16,0,0],
    ],

    index = Multiindex,
    columns = pd.MultiIndex.from_product([['delhi', 'mumbai'], ['avg_packge', 'students']])

)

branch_df3

              delhi              mumbai
         avg_packge students avg_packge students
cse 2019          1        2          0        0
    2020          3        4          0        0
    2021          5        6          0        0
    2022          7        8          0        0
ece 2019          9       10          0        0
    2020         11       12          0        0
    2021         13       14          0        0
    2022         15       16          0        0

In [14]:
branch_df3.loc['cse']['delhi']['avg_packge'][2019]

np.int64(1)

# Stacking and Unstacking

In [15]:
branch_df3.stack(future_stack=True).stack(future_stack=True)

cse  2019  avg_packge  delhi      1
                       mumbai     0
           students    delhi      2
                       mumbai     0
     2020  avg_packge  delhi      3
                       mumbai     0
           students    delhi      4
                       mumbai     0
     2021  avg_packge  delhi      5
                       mumbai     0
           students    delhi      6
                       mumbai     0
     2022  avg_packge  delhi      7
                       mumbai     0
           students    delhi      8
                       mumbai     0
ece  2019  avg_packge  delhi      9
                       mumbai     0
           students    delhi     10
                       mumbai     0
     2020  avg_packge  delhi     11
                       mumbai     0
           students    delhi     12
                       mumbai     0
     2021  avg_packge  delhi     13
                       mumbai     0
           students    delhi     14
                       mumbai     0
     2022  avg_packge  delhi     15
                       mumbai     0
           students    delhi     16
                       mumbai     0
dtype: int64

In [16]:
branch_df3.unstack().unstack()

delhi   avg_packge  2019  cse     1
                          ece     9
                    2020  cse     3
                          ece    11
                    2021  cse     5
                          ece    13
                    2022  cse     7
                          ece    15
        students    2019  cse     2
                          ece    10
                    2020  cse     4
                          ece    12
                    2021  cse     6
                          ece    14
                    2022  cse     8
                          ece    16
mumbai  avg_packge  2019  cse     0
                          ece     0
                    2020  cse     0
                          ece     0
                    2021  cse     0
                          ece     0
                    2022  cse     0
                          ece     0
        students    2019  cse     0
                          ece     0
                    2020  cse     0
                          ece     0
                    2021  cse     0
                          ece     0
                    2022  cse     0
                          ece     0
dtype: int64

In [17]:
# Extracing rows single

branch_df3.loc[('cse', 2021)]

delhi   avg_packge    5
        students      6
mumbai  avg_packge    0
        students      0
Name: (cse, 2021), dtype: int64

In [18]:
# multiple rows

branch_df3.loc[('cse', 2019):('ece', 2020) : 2]

              delhi              mumbai
         avg_packge students avg_packge students
cse 2019          1        2          0        0
    2021          5        6          0        0
ece 2019          9       10          0        0

In [19]:
# using iloc
branch_df3.iloc[0:5:2]

              delhi              mumbai
         avg_packge students avg_packge students
cse 2019          1        2          0        0
    2021          5        6          0        0
ece 2019          9       10          0        0

In [20]:
# single col

branch_df3['delhi']['students']

cse  2019     2
     2020     4
     2021     6
     2022     8
ece  2019    10
     2020    12
     2021    14
     2022    16
Name: students, dtype: int64

In [21]:
# multiple cols
branch_df3['delhi']

          avg_packge  students
cse 2019           1         2
    2020           3         4
    2021           5         6
    2022           7         8
ece 2019           9        10
    2020          11        12
    2021          13        14
    2022          15        16

In [22]:
branch_df3.iloc[:,0:3:2]

              delhi     mumbai
         avg_packge avg_packge
cse 2019          1          0
    2020          3          0
    2021          5          0
    2022          7          0
ece 2019          9          0
    2020         11          0
    2021         13          0
    2022         15          0

In [23]:
# both
branch_df3.iloc[[1,4] , [1,2]]

            delhi     mumbai
         students avg_packge
cse 2020        4          0
ece 2019       10          0

In [34]:
# sort index
branch_df3.sort_index(ascending = False)
branch_df3.sort_index(ascending = [False, True])  # level 0 decending level 1 ascending
branch_df3.sort_index(level = 1, ascending=False) # sort year index

              delhi              mumbai
         avg_packge students avg_packge students
ece 2022         15       16          0        0
cse 2022          7        8          0        0
ece 2021         13       14          0        0
cse 2021          5        6          0        0
ece 2020         11       12          0        0
cse 2020          3        4          0        0
ece 2019          9       10          0        0
cse 2019          1        2          0        0

In [36]:
# Multiindex dataFrame -> transpose
branch_df3.transpose()

                   cse                 ece
                  2019 2020 2021 2022 2019 2020 2021 2022
delhi  avg_packge    1    3    5    7    9   11   13   15
       students      2    4    6    8   10   12   14   16
mumbai avg_packge    0    0    0    0    0    0    0    0
       students      0    0    0    0    0    0    0    0

In [38]:
# swaplevel

branch_df3.swaplevel()
branch_df3.swaplevel(axis = 1)

         avg_packge students avg_packge students
              delhi    delhi     mumbai   mumbai
cse 2019          1        2          0        0
    2020          3        4          0        0
    2021          5        6          0        0
    2022          7        8          0        0
ece 2019          9       10          0        0
    2020         11       12          0        0
    2021         13       14          0        0
    2022         15       16          0        0

# Melt and pivet

In [40]:
# Melt

deaths = pd.read_csv("/content/time_series_covid19_deaths_global.csv")
confirm = pd.read_csv("/content/time_series_covid19_confirmed_global.csv")

In [41]:
deaths.head()

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,12/24/22,12/25/22,12/26/22,12/27/22,12/28/22,12/29/22,12/30/22,12/31/22,1/1/23,1/2/23
0,NaN,Afghanistan,33.93911,67.709953,0,0,0,0,0,0,...,7845,7846,7846,7846,7846,7847,7847,7849,7849,7849
1,NaN,Albania,41.15330,20.168300,0,0,0,0,0,0,...,3595,3595,3595,3595,3595,3595,3595,3595,3595,3595
2,NaN,Algeria,28.03390,1.659600,0,0,0,0,0,0,...,6881,6881,6881,6881,6881,6881,6881,6881,6881,6881
3,NaN,Andorra,42.50630,1.521800,0,0,0,0,0,0,...,165,165,165,165,165,165,165,165,165,165
4,NaN,Angola,-11.20270,17.873900,0,0,0,0,0,0,...,1928,1928,1928,1930,1930,1930,1930,1930,1930,1930

In [49]:
confirm

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,12/24/22,12/25/22,12/26/22,12/27/22,12/28/22,12/29/22,12/30/22,12/31/22,1/1/23,1/2/23
0,NaN,Afghanistan,33.939110,67.709953,0,0,0,0,0,0,...,207310,207399,207438,207460,207493,207511,207550,207559,207616,207627
1,NaN,Albania,41.153300,20.168300,0,0,0,0,0,0,...,333749,333749,333751,333751,333776,333776,333806,333806,333811,333812
2,NaN,Algeria,28.033900,1.659600,0,0,0,0,0,0,...,271194,271198,271198,271202,271208,271217,271223,271228,271229,271229
3,NaN,Andorra,42.506300,1.521800,0,0,0,0,0,0,...,47686,47686,47686,47686,47751,47751,47751,47751,47751,47751
4,NaN,Angola,-11.202700,17.873900,0,0,0,0,0,0,...,104973,104973,104973,105095,105095,105095,105095,105095,105095,105095
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284,NaN,West Bank and Gaza,31.952200,35.233200,0,0,0,0,0,0,...,703228,703228,703228,703228,703228,703228,703228,703228,703228,703228
285,NaN,Winter Olympics 2022,39.904200,116.407400,0,0,0,0,0,0,...,535,535,535,535,535,535,535,535,535,535
286,NaN,Yemen,15.552727,48.516388,0,0,0,0,0,0,...,11945,11945,11945,11945,11945,11945,11945,11945,11945,11945
287,NaN,Zambia,-13.133897,27.849332,0,0,0,0,0,0,...,334021,334021,334066,334108,334196,334294,334425,334425,334629,334661
288,NaN,Zimbabwe,-19.015438,29.154857,0,0,0,0,0,0,...,259981,259981,259981,259981,259981,259981,259981,259981,259981,259981

In [65]:
deaths = deaths.melt(id_vars = ['Province/State',	'Country/Region',	'Lat',	'Long'], var_name='Date', value_name='num_death')

In [67]:
confirm = confirm.melt(id_vars = ['Province/State',	'Country/Region',	'Lat',	'Long'], var_name='Date', value_name='num_case')

In [69]:
confirm.merge(deaths, on = ['Province/State',	'Country/Region',	'Lat','Long','Date'])[['Country/Region', 'Date',	'num_case',	'num_death']]

              Country/Region     Date  num_case  num_death
0                Afghanistan  1/22/20         0          0
1                    Albania  1/22/20         0          0
2                    Algeria  1/22/20         0          0
3                    Andorra  1/22/20         0          0
4                     Angola  1/22/20         0          0
...                      ...      ...       ...        ...
311248    West Bank and Gaza   1/2/23    703228       5708
311249  Winter Olympics 2022   1/2/23       535          0
311250                 Yemen   1/2/23     11945       2159
311251                Zambia   1/2/23    334661       4024
311252              Zimbabwe   1/2/23    259981       5637

[311253 rows x 4 columns]