<a href="https://colab.research.google.com/github/abdullah-621/pandas/blob/main/session_21_multiindex_objects.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# can we have multiple index? Let's try
index_val = [('cse',2019),('cse',2020),('cse',2021),('cse',2022),('ece',2019),('ece',2020),('ece',2021),('ece',2022)]

a = pd.Series([1,2,3,4,5,6,7,8], index = index_val)
a
# a[('cse', 2020)]

(cse, 2019)    1
(cse, 2020)    2
(cse, 2021)    3
(cse, 2022)    4
(ece, 2019)    5
(ece, 2020)    6
(ece, 2021)    7
(ece, 2022)    8
dtype: int64

In [ ]:
# The problem?
# a['cse']

In [ ]:
# The solution -> multiindex series(also known as Hierarchical Indexing)
# multiple index levels within a single index

In [ ]:
# how to create multiindex object
# 1. pd.MultiIndex.from_tuples()
index_val = [('cse',2019),('cse',2020),('cse',2021),('cse',2022),('ece',2019),('ece',2020),('ece',2021),('ece',2022)]
Multiindex = pd.MultiIndex.from_tuples(index_val)
Multiindex

# 2. pd.MultiIndex.from_product()
pd.MultiIndex.from_product([['cse','ece'], [2019,2020,2021,2022]])

MultiIndex([('cse', 2019),
            ('cse', 2020),
            ('cse', 2021),
            ('cse', 2022),
            ('ece', 2019),
            ('ece', 2020),
            ('ece', 2021),
            ('ece', 2022)],
           )

In [ ]:
# creating a series with multiindex object

s = pd.Series([1,2,3,4,5,6,7,8], index=Multiindex)
s

cse  2019    1
     2020    2
     2021    3
     2022    4
ece  2019    5
     2020    6
     2021    7
     2022    8
dtype: int64

In [ ]:
# how to fetch items from such a series
s[('cse',2019)]
s['cse']

2019    1
2020    2
2021    3
2022    4
dtype: int64

In [ ]:
# unstack
temp = s.unstack()
temp

     2019  2020  2021  2022
cse     1     2     3     4
ece     5     6     7     8

In [ ]:
# stack
temp.stack()

cse  2019    1
     2020    2
     2021    3
     2022    4
ece  2019    5
     2020    6
     2021    7
     2022    8
dtype: int64

In [ ]:
# Multiindex Data fream

branch_df1 = pd.DataFrame(
    [
        [1,2],
        [3,4],
        [5,6],
        [7,8],
        [9,12],
        [10,13],
        [11,15],
        [12,20]
    ],
    index = Multiindex,
    columns = ['avg_packge', 'students']
)
branch_df1

          avg_packge  students
cse 2019           1         2
    2020           3         4
    2021           5         6
    2022           7         8
ece 2019           9        12
    2020          10        13
    2021          11        15
    2022          12        20

In [ ]:
# Multiindex DataFream

branch_df2 = pd.DataFrame(
    [
      [1,2,0,0],
      [3,4,0,0],
      [5,6,0,0],
      [7,8,0,0],
    ],

    index = [2019, 2020, 2021, 2022],
    columns = pd.MultiIndex.from_product([['delhi', 'mumbai'], ['avg_packge', 'students']])

)

branch_df2

          delhi              mumbai
     avg_packge students avg_packge students
2019          1        2          0        0
2020          3        4          0        0
2021          5        6          0        0
2022          7        8          0        0

In [ ]:
branch_df2.loc[2019]['delhi']

avg_packge    1
students      2
Name: 2019, dtype: int64

In [ ]:
# Multiindex series and DataFream

branch_df3 = pd.DataFrame(
    [
      [1,2,0,0],
      [3,4,0,0],
      [5,6,0,0],
      [7,8,0,0],
      [9,10,0,0],
      [11,12,0,0],
      [13,14,0,0],
      [15,16,0,0],
    ],

    index = Multiindex,
    columns = pd.MultiIndex.from_product([['delhi', 'mumbai'], ['avg_packge', 'students']])

)

branch_df3

              delhi              mumbai
         avg_packge students avg_packge students
cse 2019          1        2          0        0
    2020          3        4          0        0
    2021          5        6          0        0
    2022          7        8          0        0
ece 2019          9       10          0        0
    2020         11       12          0        0
    2021         13       14          0        0
    2022         15       16          0        0

In [ ]:
branch_df3.loc['cse']['delhi']['avg_packge'][2019]

np.int64(1)

# Stacking and Unstacking

In [ ]:
branch_df3.stack(future_stack=True).stack(future_stack=True)

cse  2019  avg_packge  delhi      1
                       mumbai     0
           students    delhi      2
                       mumbai     0
     2020  avg_packge  delhi      3
                       mumbai     0
           students    delhi      4
                       mumbai     0
     2021  avg_packge  delhi      5
                       mumbai     0
           students    delhi      6
                       mumbai     0
     2022  avg_packge  delhi      7
                       mumbai     0
           students    delhi      8
                       mumbai     0
ece  2019  avg_packge  delhi      9
                       mumbai     0
           students    delhi     10
                       mumbai     0
     2020  avg_packge  delhi     11
                       mumbai     0
           students    delhi     12
                       mumbai     0
     2021  avg_packge  delhi     13
                       mumbai     0
           students    delhi     14
                       mumbai     0
     2022  avg_packge  delhi     15
                       mumbai     0
           students    delhi     16
                       mumbai     0
dtype: int64

In [ ]:
branch_df3.unstack().unstack()

delhi   avg_packge  2019  cse     1
                          ece     9
                    2020  cse     3
                          ece    11
                    2021  cse     5
                          ece    13
                    2022  cse     7
                          ece    15
        students    2019  cse     2
                          ece    10
                    2020  cse     4
                          ece    12
                    2021  cse     6
                          ece    14
                    2022  cse     8
                          ece    16
mumbai  avg_packge  2019  cse     0
                          ece     0
                    2020  cse     0
                          ece     0
                    2021  cse     0
                          ece     0
                    2022  cse     0
                          ece     0
        students    2019  cse     0
                          ece     0
                    2020  cse     0
                          ece     0
                    2021  cse     0
                          ece     0
                    2022  cse     0
                          ece     0
dtype: int64

In [ ]:
# Extracing rows single

branch_df3.loc[('cse', 2021)]

delhi   avg_packge    5
        students      6
mumbai  avg_packge    0
        students      0
Name: (cse, 2021), dtype: int64

In [ ]:
# multiple rows

branch_df3.loc[('cse', 2019):('ece', 2020) : 2]

              delhi              mumbai
         avg_packge students avg_packge students
cse 2019          1        2          0        0
    2021          5        6          0        0
ece 2019          9       10          0        0

In [ ]:
# using iloc
branch_df3.iloc[0:5:2]

              delhi              mumbai
         avg_packge students avg_packge students
cse 2019          1        2          0        0
    2021          5        6          0        0
ece 2019          9       10          0        0

In [ ]:
# single col

branch_df3['delhi']['students']

cse  2019     2
     2020     4
     2021     6
     2022     8
ece  2019    10
     2020    12
     2021    14
     2022    16
Name: students, dtype: int64

In [ ]:
# multiple cols
branch_df3['delhi']

          avg_packge  students
cse 2019           1         2
    2020           3         4
    2021           5         6
    2022           7         8
ece 2019           9        10
    2020          11        12
    2021          13        14
    2022          15        16

In [ ]:
branch_df3.iloc[:,0:3:2]

              delhi     mumbai
         avg_packge avg_packge
cse 2019          1          0
    2020          3          0
    2021          5          0
    2022          7          0
ece 2019          9          0
    2020         11          0
    2021         13          0
    2022         15          0

In [ ]:
# both
branch_df3.iloc[[1,4] , [1,2]]

            delhi     mumbai
         students avg_packge
cse 2020        4          0
ece 2019       10          0

In [ ]:
# sort index
branch_df3.sort_index(ascending = False)
branch_df3.sort_index(ascending = [False, True])  # level 0 decending level 1 ascending
branch_df3.sort_index(level = 1, ascending=False) # sort year index

              delhi              mumbai
         avg_packge students avg_packge students
ece 2022         15       16          0        0
cse 2022          7        8          0        0
ece 2021         13       14          0        0
cse 2021          5        6          0        0
ece 2020         11       12          0        0
cse 2020          3        4          0        0
ece 2019          9       10          0        0
cse 2019          1        2          0        0

In [ ]:
# Multiindex dataFrame -> transpose
branch_df3.transpose()

                   cse                 ece
                  2019 2020 2021 2022 2019 2020 2021 2022
delhi  avg_packge    1    3    5    7    9   11   13   15
       students      2    4    6    8   10   12   14   16
mumbai avg_packge    0    0    0    0    0    0    0    0
       students      0    0    0    0    0    0    0    0

In [ ]:
# swaplevel

branch_df3.swaplevel()
branch_df3.swaplevel(axis = 1)

         avg_packge students avg_packge students
              delhi    delhi     mumbai   mumbai
cse 2019          1        2          0        0
    2020          3        4          0        0
    2021          5        6          0        0
    2022          7        8          0        0
ece 2019          9       10          0        0
    2020         11       12          0        0
    2021         13       14          0        0
    2022         15       16          0        0

# Melt and pivet

In [ ]:
# Melt

deaths = pd.read_csv("/content/time_series_covid19_deaths_global.csv")
confirm = pd.read_csv("/content/time_series_covid19_confirmed_global.csv")

In [ ]:
deaths.head()

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,12/24/22,12/25/22,12/26/22,12/27/22,12/28/22,12/29/22,12/30/22,12/31/22,1/1/23,1/2/23
0,NaN,Afghanistan,33.93911,67.709953,0,0,0,0,0,0,...,7845,7846,7846,7846,7846,7847,7847,7849,7849,7849
1,NaN,Albania,41.15330,20.168300,0,0,0,0,0,0,...,3595,3595,3595,3595,3595,3595,3595,3595,3595,3595
2,NaN,Algeria,28.03390,1.659600,0,0,0,0,0,0,...,6881,6881,6881,6881,6881,6881,6881,6881,6881,6881
3,NaN,Andorra,42.50630,1.521800,0,0,0,0,0,0,...,165,165,165,165,165,165,165,165,165,165
4,NaN,Angola,-11.20270,17.873900,0,0,0,0,0,0,...,1928,1928,1928,1930,1930,1930,1930,1930,1930,1930

In [ ]:
confirm

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,12/24/22,12/25/22,12/26/22,12/27/22,12/28/22,12/29/22,12/30/22,12/31/22,1/1/23,1/2/23
0,NaN,Afghanistan,33.939110,67.709953,0,0,0,0,0,0,...,207310,207399,207438,207460,207493,207511,207550,207559,207616,207627
1,NaN,Albania,41.153300,20.168300,0,0,0,0,0,0,...,333749,333749,333751,333751,333776,333776,333806,333806,333811,333812
2,NaN,Algeria,28.033900,1.659600,0,0,0,0,0,0,...,271194,271198,271198,271202,271208,271217,271223,271228,271229,271229
3,NaN,Andorra,42.506300,1.521800,0,0,0,0,0,0,...,47686,47686,47686,47686,47751,47751,47751,47751,47751,47751
4,NaN,Angola,-11.202700,17.873900,0,0,0,0,0,0,...,104973,104973,104973,105095,105095,105095,105095,105095,105095,105095
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284,NaN,West Bank and Gaza,31.952200,35.233200,0,0,0,0,0,0,...,703228,703228,703228,703228,703228,703228,703228,703228,703228,703228
285,NaN,Winter Olympics 2022,39.904200,116.407400,0,0,0,0,0,0,...,535,535,535,535,535,535,535,535,535,535
286,NaN,Yemen,15.552727,48.516388,0,0,0,0,0,0,...,11945,11945,11945,11945,11945,11945,11945,11945,11945,11945
287,NaN,Zambia,-13.133897,27.849332,0,0,0,0,0,0,...,334021,334021,334066,334108,334196,334294,334425,334425,334629,334661
288,NaN,Zimbabwe,-19.015438,29.154857,0,0,0,0,0,0,...,259981,259981,259981,259981,259981,259981,259981,259981,259981,259981

In [ ]:
deaths = deaths.melt(id_vars = ['Province/State',	'Country/Region',	'Lat',	'Long'], var_name='Date', value_name='num_death')

In [ ]:
confirm = confirm.melt(id_vars = ['Province/State',	'Country/Region',	'Lat',	'Long'], var_name='Date', value_name='num_case')

In [ ]:
confirm.merge(deaths, on = ['Province/State',	'Country/Region',	'Lat','Long','Date'])[['Country/Region', 'Date',	'num_case',	'num_death']]

              Country/Region     Date  num_case  num_death
0                Afghanistan  1/22/20         0          0
1                    Albania  1/22/20         0          0
2                    Algeria  1/22/20         0          0
3                    Andorra  1/22/20         0          0
4                     Angola  1/22/20         0          0
...                      ...      ...       ...        ...
311248    West Bank and Gaza   1/2/23    703228       5708
311249  Winter Olympics 2022   1/2/23       535          0
311250                 Yemen   1/2/23     11945       2159
311251                Zambia   1/2/23    334661       4024
311252              Zimbabwe   1/2/23    259981       5637

[311253 rows x 4 columns]

# Pivot Table
 pd.pivot_table(data,
             values=None,
              index=None,
              columns=None,
              aggfunc='mean',
              fill_value=None)

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns

In [ ]:
df = sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
df.groupby('sex', observed=False)[['total_bill']].mean()

        total_bill
sex
Male     20.744076
Female   18.056897

In [ ]:
df.groupby(['sex', 'smoker'], observed=False)[['total_bill']].mean().unstack()

       total_bill
smoker        Yes         No
sex
Male    22.284500  19.791237
Female  17.977879  18.105185

In [ ]:
df.pivot_table(index = 'sex', columns = 'smoker', values = 'total_bill', observed=False)

smoker        Yes         No
sex
Male    22.284500  19.791237
Female  17.977879  18.105185

In [ ]:
# aggfunc

pd.pivot_table(df, index = 'sex', columns = 'smoker', values = 'total_bill', aggfunc = 'sum', observed=False)

smoker      Yes       No
sex
Male    1337.07  1919.75
Female   593.27   977.68

In [ ]:
pd.pivot_table(df, index = 'sex', columns = 'smoker', aggfunc = 'sum', observed=True)

TypeError: category type does not support sum operations

In [ ]:
# multidimensional

pd.pivot_table(df, index = ['sex', 'smoker'], columns=['day', 'time'], aggfunc={'size':'mean', 'tip' : 'max', 'total_bill' : 'sum'}, margins=True, observed=False)

                   size                                                 \
day                Thur              Fri                 Sat       Sun
time              Lunch Dinner     Lunch    Dinner    Dinner    Dinner
sex    smoker
Male   Yes     2.300000    NaN  1.666667  2.400000  2.629630  2.600000
       No      2.500000    NaN       NaN  2.000000  2.656250  2.883721
Female Yes     2.428571    NaN  2.000000  2.000000  2.200000  2.500000
       No      2.500000    2.0  3.000000  2.000000  2.307692  3.071429
All            2.459016    2.0  2.000000  2.166667  2.517241  2.842105

                          tip               ...       total_bill         \
day                 All  Thur          Fri  ...   All       Thur
time                    Lunch Dinner Lunch  ...            Lunch Dinner
sex    smoker                               ...
Male   Yes     2.500000  5.00    NaN  2.20  ...  10.0     191.71   0.00
       No      2.711340  6.70    NaN   NaN  ...   9.0     369.73   0.00
Female Yes     2.242424  5.00    NaN  3.48  ...   6.5     134.53   0.00
       No      2.592593  5.17    3.0  3.00  ...   5.2     381.58  18.78
All            2.569672  6.70    3.0  3.48  ...  10.0    1077.55  18.78


day              Fri           Sat            Sun               All
time           Lunch  Dinner Lunch   Dinner Lunch   Dinner
sex    smoker
Male   Yes     34.16  129.46   0.0   589.62   0.0   392.12  1337.07
       No       0.00   34.95   0.0   637.73   0.0   877.34  1919.75
Female Yes     39.78   48.80   0.0   304.00   0.0    66.16   593.27
       No      15.98   22.75   0.0   247.05   0.0   291.54   977.68
All            89.92  235.96   NaN  1778.40   NaN  1627.16  4827.77

[5 rows x 23 columns]

In [ ]:
# # margins

pd.pivot_table(df, index = 'sex', columns = 'smoker', values = 'total_bill', margins=True, observed= True)

smoker        Yes         No        All
sex
Male    22.284500  19.791237  20.744076
Female  17.977879  18.105185  18.056897
All     20.756344  19.188278  19.785943

In [ ]:
# plotting graphs

df = pd.read_csv('/content/expense_data.csv')
df.head()

,Date,Account,Category,Subcategory,Note,INR,Income/Expense,Note.1,Amount,Currency,Account.1
0,3/2/2022 10:11,CUB - online payment,Food,NaN,Brownie,50.0,Expense,NaN,50.0,INR,50.0
1,3/2/2022 10:11,CUB - online payment,Other,NaN,To lended people,300.0,Expense,NaN,300.0,INR,300.0
2,3/1/2022 19:50,CUB - online payment,Food,NaN,Dinner,78.0,Expense,NaN,78.0,INR,78.0
3,3/1/2022 18:56,CUB - online payment,Transportation,NaN,Metro,30.0,Expense,NaN,30.0,INR,30.0
4,3/1/2022 18:22,CUB - online payment,Food,NaN,Snacks,67.0,Expense,NaN,67.0,INR,67.0